version: "3.7"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PORT_FRONTEND=$PORT_FRONTEND
    container_name: webfrontend
    depends_on:
      - core
    ports:
      - "3000:${PORT_FRONTEND}"
    environment:
      - REACT_APP_CORE_URL=http://localhost:8000

  core:
    container_name: webcore
    image: ghcr.io/julianfrattini/cira:0.9.7
    ports:
      - "8000:8000"
