version: "3.7"

services:
  frontend:
    build: ./frontend
    container_name: webfrontend
    depends_on:
      - core
    ports:
      - "3000:3001"
    environment:
      - PORT=3001
    networks:
      cira-web:
        ipv4_address: 172.19.0.3

  core:
    container_name: webcore
    image: ghcr.io/julianfrattini/cira:0.9.7
    ports:
      - "8000:8000"

networks:
  cira-web:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/16
